# Generated by Django 3.1.6 on 2021-05-09 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Completed', 'COMPLETED')], max_length=10)),
                ('color', models.CharField(choices=[('Red', 'RED'), ('Green', 'GREEN'), ('Blue', 'BLUE')], max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
