# Generated by Django 3.2.6 on 2021-12-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
